CREATE TABLE IF NOT EXISTS USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NULL DEFAULT NULL ,
    mobile VARCHAR(15) NULL DEFAULT NULL ,
    email VARCHAR(50) NULL DEFAULT NULL ,
    city VARCHAR(50) NULL DEFAULT NULL ,
    state VARCHAR(50) NULL DEFAULT NULL ,
    country VARCHAR(50) NULL DEFAULT NULL ,
    pin VARCHAR(10) NULL DEFAULT NULL ,
    PRIMARY KEY (ID)
)